import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Language = 'en' | 'mr' | 'hi';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.crops': 'Crop Management',
    'nav.health': 'AI Health Monitor',
    'nav.marketplace': 'B2B Marketplace',
    'nav.orders': 'My Orders',
    'nav.negotiations': 'Negotiations',
    'nav.inventory': 'My Inventory',
    'nav.weather': 'Weather',
    'nav.marketPrices': 'Market Prices',
    'nav.encyclopedia': 'Crop Encyclopedia',
    'nav.financial': 'Financial',
    'nav.profile': 'My Profile',
    'nav.feedback': 'Feedback',
    'nav.chat': 'B2B Chat',
    
    // Dashboard
    'dash.welcome': 'Welcome',
    'dash.farm': 'Your Farm',
    'dash.totalCrops': 'Total Crops',
    'dash.healthyCrops': 'Healthy Crops',
    'dash.pendingOrders': 'Pending Orders',
    'dash.cropAlerts': 'Crop Alerts',
    'dash.cropStatus': 'Crop Status',
    'dash.active': 'active',
    'dash.recentOrders': 'Recent Orders',
    'dash.viewAll': 'View all',
    
    // Dashboard Sub-navigation
    'dash.subnav.overview': 'Overview',
    'dash.subnav.weather': 'Weather',
    'dash.subnav.marketPrices': 'Market Prices',
    'dash.subnav.encyclopedia': 'Crop Encyclopedia',
    
    // Weather Module
    'weather.title': 'Weather Intelligence',
    'weather.current': 'Current Weather',
    'weather.forecast7d': '7-Day Forecast',
    'weather.forecast48h': '48-Hour Forecast',
    'weather.humidity': 'Humidity',
    'weather.windSpeed': 'Wind Speed',
    'weather.uvIndex': 'UV Index',
    'weather.rainfall': 'Rainfall',
    'weather.soilMoisture': 'Soil Moisture',
    'weather.feelsLike': 'Feels like',
    'weather.alerts': 'Weather Alerts',
    'weather.noAlerts': 'No active alerts',
    'weather.recommendations': 'Crop Recommendations',
    'weather.advisory.title': "Farmer's Advisory",
    'weather.advisory.sprayWarning': 'Avoid spraying pesticides due to predicted rain',
    'weather.advisory.heatWarning': 'High heat expected, increase irrigation',
    'weather.location.detecting': 'Detecting location...',
    'weather.location.retry': 'Retry',
    
    // Market Prices
    'market.title': 'Local Market Intelligence',
    'market.subtitle': 'Real-time mandi prices and market trends across India',
    'market.search': 'Search crops...',
    'market.filter.state': 'All States',
    'market.filter.district': 'All Districts',
    'market.filter.taluka': 'All Talukas',
    'market.filter.crop': 'All Crops',
    'market.crop': 'Crop',
    'market.variety': 'Variety',
    'market.market': 'Market',
    'market.minPrice': 'Min Price',
    'market.maxPrice': 'Max Price',
    'market.modalPrice': 'Modal Price',
    'market.trend': 'Trend',
    'market.avgPrice': 'avg. per quintal',
    'market.vsLastWeek': 'vs last week',
    'market.mandiPrices': 'Mandi Prices',
    'market.priceTicker': 'Live Price Ticker',
    'market.smartSuggestion': 'Smart Suggestion',
    'market.roiPrediction': 'ROI Prediction',
    'market.highestRoi': 'Highest ROI Crops',
    'market.priceChart': 'Price Trend (6 Months)',
    'market.sortBy': 'Sort by',
    'market.volume': 'Volume',
    'market.quality': 'Quality',
    'market.viewAnalytics': 'View Analytics',
    'market.analytics.title': 'Market Analytics',
    'market.analytics.overview': 'Overview',
    'market.analytics.trends': 'Trends',
    'market.analytics.factors': 'Market Factors',
    'market.analytics.currentPrice': 'Current Price',
    'market.analytics.predictedPrice': 'Predicted Price',
    'market.analytics.confidence': 'AI Confidence',
    'market.analytics.season': 'Season',
    'market.analytics.demand': 'Demand',
    'market.analytics.supply': 'Supply',
    'market.analytics.profitPotential': 'Profit Potential',
    'market.analytics.favorableSell': 'Favorable Time to Sell',
    'market.analytics.holdStore': 'Hold or Store',
    
    // Crop Encyclopedia
    'encyclo.title': 'Crop Encyclopedia',
    'encyclo.subtitle': 'Comprehensive guide to crops, cultivation practices, and pest management',
    'encyclo.search': 'Search crops, varieties, or growing tips...',
    'encyclo.plantingGuide': 'Planting Guide',
    'encyclo.soilRequirements': 'Soil Requirements',
    'encyclo.sowingDepth': 'Sowing Depth',
    'encyclo.waterFrequency': 'Water Frequency',
    'encyclo.seasonCalendar': 'Season Calendar',
    'encyclo.sowing': 'Sowing',
    'encyclo.growing': 'Growing',
    'encyclo.harvest': 'Harvest',
    'encyclo.pestDisease': 'Pest & Disease Management',
    'encyclo.organicSolution': 'Organic Solution',
    'encyclo.chemicalSolution': 'Chemical Solution',
    'encyclo.varietyCount': 'varieties',
    'encyclo.aiSearch': 'AI Crop Search',
    'encyclo.searchPlaceholder': 'Search any crop (e.g., wheat, rice, cotton)...',
    'encyclo.fertilizerGuide': 'Fertilizer Guide',
    'encyclo.growingStages': 'Growing Stages',
    'encyclo.pestManagement': 'Pest Management',
    'encyclo.suitableRegions': 'Suitable Regions',
    'encyclo.organic': 'Organic',
    'encyclo.chemical': 'Chemical',
    'encyclo.symptoms': 'Symptoms',
    'encyclo.organicControl': 'Organic Control',
    'encyclo.chemicalControl': 'Chemical Control',
    'encyclo.backToSearch': 'Back to Search',
    'encyclo.temperature': 'Temperature',
    'encyclo.duration': 'Crop Duration',
    'encyclo.water': 'Water',
    'encyclo.sunlight': 'Sunlight',
    'encyclo.soilType': 'Soil Type',
    'encyclo.soilPH': 'Soil pH',
    'encyclo.spacing': 'Spacing',
    'encyclo.germination': 'Germination Time',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.retry': 'Retry',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.close': 'Close',
    'common.apply': 'Apply',
    'common.clear': 'Clear',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.noData': 'No data available',
    'common.readMore': 'Read more',
    'common.showLess': 'Show less',
    
    // Marketplace
    'market.secureCheckout': 'Secure Checkout',
    'market.orderSummary': 'Order Summary',
    'market.unitPrice': 'Unit Price',
    'market.origination': 'Origination',
    'market.adjustQuantity': 'Adjust Quantity',
    'market.netTotal': 'Net Total',
    'market.transactionFee': 'Transaction Fee',
    'market.deliveryEst': 'Delivery Est.',
    'market.totalPayable': 'Total Payable',
    'market.logisticsDetails': 'Logistics Details',
    'market.consigneeAddress': 'Consignee Address',
    'market.city': 'City',
    'market.zipCode': 'ZIP / Postcode',
    'market.state': 'State / Province',
    'market.supplierVerified': 'Supplier Verified',
    'market.merchantName': 'Merchant Name',
    'market.confirmSource': 'Confirm & Source Stock',
    'market.securing': 'Securing Transaction...',
    'market.min': 'Min',
    'market.maxAvailable': 'Max Available',
  },
  mr: {
    // Navigation
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.crops': 'पीक व्यवस्थापन',
    'nav.health': 'कृत्रिम बुद्धिमत्ता आरोग्य',
    'nav.marketplace': 'बी2बी मार्केटप्लेस',
    'nav.orders': 'माझ्या ऑर्डर्स',
    'nav.negotiations': 'वाटाघाटी',
    'nav.inventory': 'माझी इन्व्हेंटरी',
    'nav.weather': 'हवामान',
    'nav.marketPrices': 'बाजार भाव',
    'nav.encyclopedia': 'पीक माहिती',
    'nav.financial': 'आर्थिक',
    'nav.profile': 'माझे प्रोफाइल',
    'nav.feedback': 'अभिप्राय',
    'nav.chat': 'बी2बी चॅट',
    
    // Dashboard
    'dash.welcome': 'स्वागत आहे',
    'dash.farm': 'तुमचे शेत',
    'dash.totalCrops': 'एकूण पिके',
    'dash.healthyCrops': 'निरोगी पिके',
    'dash.pendingOrders': 'प्रलंबित ऑर्डर्स',
    'dash.cropAlerts': 'पीक सूचना',
    'dash.cropStatus': 'पिकाची स्थिती',
    'dash.active': 'सक्रिय',
    'dash.recentOrders': 'अलीकडील ऑर्डर्स',
    'dash.viewAll': 'सर्व पहा',
    
    // Dashboard Sub-navigation
    'dash.subnav.overview': 'आढावा',
    'dash.subnav.weather': 'हवामान',
    'dash.subnav.marketPrices': 'बाजार भाव',
    'dash.subnav.encyclopedia': 'पीक माहिती',
    
    // Weather Module
    'weather.title': 'हवामान बुद्धिमत्ता',
    'weather.current': 'सध्याचे हवामान',
    'weather.forecast7d': '7-दिवसीय अंदाज',
    'weather.forecast48h': '48-तासांचा अंदाज',
    'weather.humidity': 'आर्द्रता',
    'weather.windSpeed': 'वाऱ्याचा वेग',
    'weather.uvIndex': 'यूवी निर्देशांक',
    'weather.rainfall': 'पाऊस',
    'weather.soilMoisture': 'मातीतील ओलावा',
    'weather.feelsLike': 'असे वाटते',
    'weather.alerts': 'हवामान सूचना',
    'weather.noAlerts': 'सक्रिय सूचना नाहीत',
    'weather.recommendations': 'पीक शिफारसी',
    'weather.advisory.title': 'शेतकरी सल्ला',
    'weather.advisory.sprayWarning': 'अंदाजित पावसामुळे कीटकनाशके फवारणे टाळा',
    'weather.advisory.heatWarning': 'उष्णता वाढण्याची शक्यता, सिंचन वाढवा',
    'weather.location.detecting': 'स्थान शोधत आहे...',
    'weather.location.retry': 'पुन्हा प्रयत्न करा',
    
    // Market Prices
    'market.title': 'स्थानिक बाजार बुद्धिमत्ता',
    'market.subtitle': 'भारतभरातील रिअल-टाइम मंडी भाव आणि बाजार ट्रेंड',
    'market.search': 'पिके शोधा...',
    'market.filter.state': 'सर्व राज्ये',
    'market.filter.district': 'सर्व जिल्हे',
    'market.filter.taluka': 'सर्व तालुके',
    'market.filter.crop': 'सर्व पिके',
    'market.crop': 'पीक',
    'market.variety': 'वाण',
    'market.market': 'बाजार',
    'market.minPrice': 'किमान किंमत',
    'market.maxPrice': 'कमाल किंमत',
    'market.modalPrice': 'मोडाल किंमत',
    'market.trend': 'ट्रेंड',
    'market.avgPrice': 'सरासरी प्रति क्विंटल',
    'market.vsLastWeek': 'मागील आठवड्यापेक्षा',
    'market.mandiPrices': 'मंडी भाव',
    'market.priceTicker': 'थेट भाव टिकर',
    'market.smartSuggestion': 'स्मार्ट सूचना',
    'market.roiPrediction': 'रिटर्न अंदाज',
    'market.highestRoi': 'सर्वोच्च रिटर्न पिके',
    'market.priceChart': 'किंमत ट्रेंड (6 महिने)',
    'market.sortBy': 'क्रमवारी',
    'market.volume': 'व्हॉल्यूम',
    'market.quality': 'गुणवत्ता',
    'market.viewAnalytics': 'विश्लेषण पहा',
    'market.analytics.title': 'बाजार विश्लेषण',
    'market.analytics.overview': 'अवलोकन',
    'market.analytics.trends': 'रुझान',
    'market.analytics.factors': 'बाजार घटक',
    'market.analytics.currentPrice': 'वर्तमान मूल्य',
    'market.analytics.predictedPrice': 'अनुमानित मूल्य',
    'market.analytics.confidence': 'AI विश्वास',
    'market.analytics.season': 'मौसम',
    'market.analytics.demand': 'मांग',
    'market.analytics.supply': 'आपूर्ति',
    'market.analytics.profitPotential': 'लाभ क्षमता',
    'market.analytics.favorableSell': 'बेचने का अनुकूल समय',
    'market.analytics.holdStore': 'रोकें या संग्रहीत करें',
    
    // Crop Encyclopedia
    'encyclo.title': 'पीक माहितीकोश',
    'encyclo.subtitle': 'पिके, लागवड पद्धती आणि कीटक व्यवस्थापनाचे व्यापक मार्गदर्शक',
    'encyclo.search': 'पिके, वाण किंवा लागवड टिप्स शोधा...',
    'encyclo.plantingGuide': 'लागवड मार्गदर्शक',
    'encyclo.soilRequirements': 'माती आवश्यकता',
    'encyclo.sowingDepth': 'पेरणी खोली',
    'encyclo.waterFrequency': 'पाणी वारंवारता',
    'encyclo.seasonCalendar': 'हंगाम कॅलेंडर',
    'encyclo.sowing': 'पेरणी',
    'encyclo.growing': 'वाढ',
    'encyclo.harvest': 'कापणी',
    'encyclo.pestDisease': 'कीटक आणि रोग व्यवस्थापन',
    'encyclo.organicSolution': 'सेंद्रिय उपाय',
    'encyclo.chemicalSolution': 'रासायनिक उपाय',
    'encyclo.varietyCount': 'वाण',
    'encyclo.aiSearch': 'AI पीक शोध',
    'encyclo.searchPlaceholder': 'पीक शोधा (उदा. गहू, तांदूळ, कापूस)...',
    'encyclo.fertilizerGuide': 'खत मार्गदर्शक',
    'encyclo.growingStages': 'वाढीच्या टप्पे',
    'encyclo.pestManagement': 'कीट व्यवस्थापन',
    'encyclo.suitableRegions': 'योग्य प्रदेश',
    'encyclo.organic': 'सेंद्रिय',
    'encyclo.chemical': 'रासायनिक',
    'encyclo.symptoms': 'लक्षणे',
    'encyclo.organicControl': 'सेंद्रिय उपाय',
    'encyclo.chemicalControl': 'रासायनिक उपाय',
    'encyclo.backToSearch': 'मागे जा',
    'encyclo.temperature': 'तापमान',
    'encyclo.duration': 'पिक कालावधी',
    'encyclo.water': 'पाणी',
    'encyclo.sunlight': 'सूर्यप्रकाश',
    'encyclo.soilType': 'माती प्रकार',
    'encyclo.soilPH': 'pH स्तर',
    'encyclo.spacing': 'अंतर',
    'encyclo.germination': 'अंकुरण काल',
    
    // Common
    'common.loading': 'लोड होत आहे...',
    'common.error': 'त्रुटी',
    'common.retry': 'पुन्हा प्रयत्न करा',
    'common.cancel': 'रद्द करा',
    'common.save': 'जतन करा',
    'common.delete': 'हटवा',
    'common.edit': 'संपादित करा',
    'common.view': 'पहा',
    'common.close': 'बंद करा',
    'common.apply': 'लागू करा',
    'common.clear': 'साफ करा',
    'common.search': 'शोधा',
    'common.filter': 'फिल्टर',
    'common.sort': 'क्रमवारी',
    'common.noData': 'डेटा उपलब्ध नाही',
    'common.readMore': 'अधिक वाचा',
    'common.showLess': 'कमी दाखवा',
    
    // Marketplace
    'market.secureCheckout': 'सुरक्षित चेकआउट',
    'market.orderSummary': 'ऑर्डर सारांश',
    'market.unitPrice': 'प्रति युनिट किंमत',
    'market.origination': 'मूळ स्थान',
    'market.adjustQuantity': 'प्रमाण समायोजित करा',
    'market.netTotal': 'एकूण किंमत',
    'market.transactionFee': 'व्यवहार शुल्क',
    'market.deliveryEst': 'वितरण अंदाज',
    'market.totalPayable': 'एकूण देय',
    'market.logisticsDetails': 'लॉजिस्टिक्स तपशील',
    'market.consigneeAddress': 'प्राप्तकर्त्याचा पत्ता',
    'market.city': 'शहर',
    'market.zipCode': 'पिन कोड',
    'market.state': 'राज्य / प्रांत',
    'market.supplierVerified': 'पुरवठादार प्रमाणित',
    'market.merchantName': 'विक्रेत्याचे नाव',
    'market.confirmSource': 'पुष्टी करा आणि खरेदी करा',
    'market.securing': 'व्यवहार सुरक्षित करत आहे...',
    'market.min': 'किमान',
    'market.maxAvailable': 'कमाल उपलब्ध',
  },
  hi: {
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.crops': 'फसल प्रबंधन',
    'nav.health': 'एआई स्वास्थ्य',
    'nav.marketplace': 'बी2बी मार्केटप्लेस',
    'nav.orders': 'मेरे ऑर्डर',
    'nav.negotiations': 'वार्ता',
    'nav.inventory': 'मेरा स्टॉक',
    'nav.weather': 'मौसम',
    'nav.marketPrices': 'बाजार भाव',
    'nav.encyclopedia': 'फसल ज्ञानकोश',
    'nav.financial': 'वित्तीय',
    'nav.profile': 'मेरी प्रोफाइल',
    'nav.feedback': 'प्रतिक्रिया',
    'nav.chat': 'बी2बी चैट',
    
    // Dashboard
    'dash.welcome': 'स्वागत है',
    'dash.farm': 'आपका खेत',
    'dash.totalCrops': 'कुल फसलें',
    'dash.healthyCrops': 'स्वस्थ फसलें',
    'dash.pendingOrders': 'लंबित आदेश',
    'dash.cropAlerts': 'फसल अलर्ट',
    'dash.cropStatus': 'फसल की स्थिति',
    'dash.active': 'सक्रिय',
    'dash.recentOrders': 'हाल के ऑर्डर',
    'dash.viewAll': 'सभी देखें',
    
    // Dashboard Sub-navigation
    'dash.subnav.overview': 'अवलोकन',
    'dash.subnav.weather': 'मौसम',
    'dash.subnav.marketPrices': 'बाजार भाव',
    'dash.subnav.encyclopedia': 'फसल ज्ञानकोश',
    
    // Weather Module
    'weather.title': 'मौसम बुद्धिमत्ता',
    'weather.current': 'वर्तमान मौसम',
    'weather.forecast7d': '7-दिवसीय पूर्वानुमान',
    'weather.forecast48h': '48-घंटे का पूर्वानुमान',
    'weather.humidity': 'आर्द्रता',
    'weather.windSpeed': 'हवा की गति',
    'weather.uvIndex': 'यूवी इंडेक्स',
    'weather.rainfall': 'वर्षा',
    'weather.soilMoisture': 'मिट्टी की नमी',
    'weather.feelsLike': 'महसूस होता है',
    'weather.alerts': 'मौसम अलर्ट',
    'weather.noAlerts': 'कोई सक्रिय अलर्ट नहीं',
    'weather.recommendations': 'फसल सिफारिशें',
    'weather.advisory.title': 'किसान सलाह',
    'weather.advisory.sprayWarning': 'अनुमानित बारिश के कारण कीटनाशक छिड़काव से बचें',
    'weather.advisory.heatWarning': 'अत्यधिक गर्मी की संभावना, सिंचाई बढ़ाएं',
    'weather.location.detecting': 'स्थान का पता लगा रहा है...',
    'weather.location.retry': 'पुनः प्रयास करें',
    
    // Market Prices
    'market.title': 'स्थानीय बाजार बुद्धिमत्ता',
    'market.subtitle': 'भारत में रियल-टाइम मंडी भाव और बाजार रुझान',
    'market.search': 'फसलें खोजें...',
    'market.filter.state': 'सभी राज्य',
    'market.filter.district': 'सभी जिले',
    'market.filter.taluka': 'सभी तालुका',
    'market.filter.crop': 'सभी फसलें',
    'market.crop': 'फसल',
    'market.variety': 'किस्म',
    'market.market': 'बाजार',
    'market.minPrice': 'न्यूनतम मूल्य',
    'market.maxPrice': 'अधिकतम मूल्य',
    'market.modalPrice': 'मोडाल मूल्य',
    'market.trend': 'रुझान',
    'market.avgPrice': 'औसत प्रति क्विंटल',
    'market.vsLastWeek': 'पिछले सप्ताह से',
    'market.mandiPrices': 'मंडी भाव',
    'market.priceTicker': 'लाइव भाव टिकर',
    'market.smartSuggestion': 'स्मार्ट सुझाव',
    'market.roiPrediction': 'रिटर्न अनुमान',
    'market.highestRoi': 'सर्वोच्च रिटर्न फसलें',
    'market.priceChart': 'मूल्य रुझान (6 महीने)',
    'market.sortBy': 'क्रमबद्ध करें',
    'market.volume': 'वॉल्यूम',
    'market.quality': 'गुणवत्ता',
    'market.viewAnalytics': 'विश्लेषण देखें',
    'market.analytics.title': 'बाजार विश्लेषण',
    'market.analytics.overview': 'अवलोकन',
    'market.analytics.trends': 'रुझान',
    'market.analytics.factors': 'बाजार कारक',
    'market.analytics.currentPrice': 'वर्तमान मूल्य',
    'market.analytics.predictedPrice': 'अनुमानित मूल्य',
    'market.analytics.confidence': 'AI विश्वास',
    'market.analytics.season': 'मौसम',
    'market.analytics.demand': 'मांग',
    'market.analytics.supply': 'आपूर्ति',
    'market.analytics.profitPotential': 'लाभ क्षमता',
    'market.analytics.favorableSell': 'बेचने का अनुकूल समय',
    'market.analytics.holdStore': 'रोकें या संग्रहीत करें',
    
    // Crop Encyclopedia
    'encyclo.title': 'फसल ज्ञानकोश',
    'encyclo.subtitle': 'फसलों, खेती प्रथाओं और कीट प्रबंधन का व्यापक मार्गदर्शक',
    'encyclo.search': 'फसलें, किस्में या खेती टिप्स खोजें...',
    'encyclo.plantingGuide': 'बुआई मार्गदर्शिका',
    'encyclo.soilRequirements': 'मिट्टी की आवश्यकताएं',
    'encyclo.sowingDepth': 'बुआई की गहराई',
    'encyclo.waterFrequency': 'पानी की आवृत्ति',
    'encyclo.seasonCalendar': 'मौसम कैलेंडर',
    'encyclo.sowing': 'बुआई',
    'encyclo.growing': 'विकास',
    'encyclo.harvest': 'कटाई',
    'encyclo.pestDisease': 'कीट और रोग प्रबंधन',
    'encyclo.organicSolution': 'जैविक समाधान',
    'encyclo.chemicalSolution': 'रासायनिक समाधान',
    'encyclo.varietyCount': 'किस्में',
    'encyclo.aiSearch': 'AI फसल खोज',
    'encyclo.searchPlaceholder': 'फसल खोजें (जैसे गेहूं, चावल, कपास)...',
    'encyclo.fertilizerGuide': 'उर्वरक मार्गदर्शिका',
    'encyclo.growingStages': 'विकास चरण',
    'encyclo.pestManagement': 'कीट प्रबंधन',
    'encyclo.suitableRegions': 'उपयुक्त क्षेत्र',
    'encyclo.organic': 'जैविक',
    'encyclo.chemical': 'रासायनिक',
    'encyclo.symptoms': 'लक्षण',
    'encyclo.organicControl': 'जैविक नियंत्रण',
    'encyclo.chemicalControl': 'रासायनिक नियंत्रण',
    'encyclo.backToSearch': 'वापस जाएं',
    'encyclo.temperature': 'तापमान',
    'encyclo.duration': 'फसल अवधि',
    'encyclo.water': 'पानी',
    'encyclo.sunlight': 'धूप',
    'encyclo.soilType': 'मिट्टी का प्रकार',
    'encyclo.soilPH': 'pH स्तर',
    'encyclo.spacing': 'दूरी',
    'encyclo.germination': 'अंकुरण समय',
    
    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.retry': 'पुनः प्रयास करें',
    'common.cancel': 'रद्द करें',
    'common.save': 'सहेजें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.view': 'देखें',
    'common.close': 'बंद करें',
    'common.apply': 'लागू करें',
    'common.clear': 'साफ करें',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
    'common.sort': 'क्रमबद्ध करें',
    'common.noData': 'कोई डेटा उपलब्ध नहीं',
    'common.readMore': 'और पढ़ें',
    'common.showLess': 'कम दिखाएं',
    
    // Marketplace
    'market.secureCheckout': 'सुरक्षित चेकआउट',
    'market.orderSummary': 'ऑर्डर सारांश',
    'market.unitPrice': 'प्रति यूनिट मूल्य',
    'market.origination': 'उत्पत्ति',
    'market.adjustQuantity': 'मात्रा समायोजित करें',
    'market.netTotal': 'कुल मूल्य',
    'market.transactionFee': 'लेन-देन शुल्क',
    'market.deliveryEst': 'वितरण अनुमान',
    'market.totalPayable': 'कुल देय',
    'market.logisticsDetails': 'रसद विवरण',
    'market.consigneeAddress': 'प्रेषिती का पता',
    'market.city': 'शहर',
    'market.zipCode': 'पिन कोड',
    'market.state': 'राज्य / प्रांत',
    'market.supplierVerified': 'आपूर्तिकर्ता सत्यापित',
    'market.merchantName': 'व्यापारी का नाम',
    'market.confirmSource': 'पुष्टि करें और खरीदें',
    'market.securing': 'लेनदेन सुरक्षित किया जा रहा है...',
    'market.min': 'न्यूनतम',
    'market.maxAvailable': 'अधिकतम उपलब्ध',
  },
};

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'en',
      setLanguage: (lang) => set({ language: lang }),
      t: (key) => {
        const lang = get().language;
        return translations[lang][key] || translations['en'][key] || key;
      },
    }),
    {
      name: 'farm-language-storage',
    }
  )
);
